---
title: Speculation across various scientific topics
author: ''
date: '2026-09-02'
slug: speculation-across-various-scientific-topics
code_folding: hide
categories:
  - science
  - bibliometrics
tags:
  - s
  - linguistics
  - language
  - bibliometrics
  - Scopus
  - research methods
subtitle: ''
summary: 'This reproducible descriptive analysis uses annual Scopus counts to compare how often records in nine query-defined literatures use a form of “speculate” in their titles, abstracts or keywords. The count is a proxy for explicit wording in indexed records and says little about the quality of the evidence.'
abstract: 'This descriptive bibliometric analysis compares, across nine query-defined literatures, the annual share of Scopus records that mention speculat* in the title, abstract or keywords. The percentage is treated as an indicator of explicit wording in indexed records. It is no direct measure of evidential quality, theoretical progress or the amount of speculation in the full literature. The queries and data are available for inspection.'
authors: []
lastmod: ''
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

<script src="{{< blogdown/postref >}}index.en_files/clipboard/clipboard.min.js"></script>
<link href="{{< blogdown/postref >}}index.en_files/xaringanExtra-clipboard/xaringanExtra-clipboard.css" rel="stylesheet" />
<script src="{{< blogdown/postref >}}index.en_files/xaringanExtra-clipboard/xaringanExtra-clipboard.js"></script>
<script>window.xaringanExtraClipboard(null, {"button":"Copy Code","success":"Copied!","error":"Press Ctrl+C to Copy"})</script>


<div id="introduction" class="section level2">
<h2>Introduction</h2>
<div class="alert alert-info" role="alert" style="padding-bottom: 0; margin-bottom: 6%;">
<p>Given all of the data that E&amp;L [Evans &amp; Levinson, 2009] cite, how could anyone maintain the notion of a universal grammar with linguistic content? Traditionally, there have been three basic strategies. First, just as we may force English grammar into the Procrustean bed of Latin grammar – that is how I was taught the structure of English in grade school – the grammars of the world’s so-called exotic languages may be forced into an abstract scheme based mainly on European languages.</p>
<p>— Tomasello (2009, p. 470)</p>
</div>
<p>Some research topics invite more explicit conjecture than others. In a review of language evolution, Paul Vogt and I noted that the field has little direct evidence to work with and a high degree of speculation (Bernabeu &amp; Vogt, 2015). Comparing fields on this score is hard, and database counts cannot rank them by how much they speculate. They can, however, show how often authors use a particular family of words in the title, abstract and keyword fields that Scopus indexes.</p>
<p>Authors who speculate in print sometimes say so, in phrases such as “we speculate that” or “it is tempting to speculate”. The share of records that contain a form of <code>speculat*</code> is therefore an indicator of explicit wording in indexed metadata. It is not a measure of how much speculation an article contains, how well supported its claims are or how mature a research area is. Conventions for hedging, abstract writing and indexing can all affect the count.</p>
<p>This post compares that share, year by year from 1980 to the present, across nine reference literatures. Six of them concern language: language evolution, language comprehension, language disorders, linguistic relativity, language teaching and the bilingual advantage. A seventh, sensorimotor simulation, is the topic of my own doctoral work on conceptual processing. The last two, artificial general intelligence and the hadron collider, lie outside the language sciences and serve as points of comparison. Speculation might be expected in the first, whereas the second is a field of large instruments and large collaborations. Each reference literature is defined by a query on the title, abstract and keywords. Within each year, the comparison counts the records that also match <code>speculat*</code> in those fields.</p>
</div>
<div id="development-the-searches" class="section level2">
<h2>Development: the searches</h2>
<p>The searches use my <a href="/2026/scopusflow-a-literature-search-you-can-rerun/">scopusflow</a> package (Bernabeu, 2026) and are run by a <a href="https://github.com/pablobernabeu/website-files/blob/master/scripts/update_post_searches.R">script in the website’s repository</a>. The counts it returns are saved with the post, so the figures can be reproduced without a Scopus API key. The nine queries are as follows.</p>
<pre class="r"><code>library(scopusflow)

years &lt;- 1980:as.integer(format(Sys.Date(), &#39;%Y&#39;))

topics &lt;- c(
  &#39;language evolution&#39;              = &#39;&quot;language evolution&quot; OR &quot;evolution of language&quot;&#39;,
  &#39;language comprehension&#39;          = &#39;&quot;language comprehension&quot;&#39;,
  &#39;language disorders&#39;              = &#39;&quot;language disorders&quot; OR &quot;language disorder&quot;&#39;,
  &#39;linguistic relativity&#39;           = &#39;&quot;linguistic relativity&quot;&#39;,
  &#39;language teaching&#39;               = &#39;&quot;language teaching&quot;&#39;,
  &#39;bilingual advantage&#39;             = &#39;&quot;bilingual advantage&quot; OR &quot;bilingual advantages&quot;&#39;,
  &#39;sensorimotor simulation&#39;         = &#39;&quot;sensorimotor simulation&quot;&#39;,
  &#39;artificial general intelligence&#39; = &#39;&quot;artificial general intelligence&quot;&#39;,
  &#39;hadron collider&#39;                 = &#39;&quot;hadron collider&quot;&#39;
)

comparisons &lt;- lapply(names(topics), function(label) {
  cmp &lt;- scopus_compare_topics(
    reference_query  = topics[[label]],
    comparison_terms = &#39;speculat*&#39;,
    years            = years,
    field            = &#39;TITLE-ABS-KEY&#39;
  )
  cmp$topic &lt;- label
  cmp
})</code></pre>
<p>For every year, <code>scopus_compare_topics()</code> counts the records that match the reference query and those that also match the comparison term. The nine comparisons therefore take 846 requests to the Scopus API. Each row of the result holds a year, the count for the reference literature, the count for the comparison and the comparison as a percentage of the reference.</p>
<pre class="r"><code>library(dplyr)
library(ggplot2)

comparisons &lt;- readRDS(&#39;searches/speculation_comparisons.rds&#39;)
retrieved &lt;- attr(comparisons, &#39;retrieved&#39;)
retrieved</code></pre>
<pre><code>#&gt; [1] &quot;2026-09-02 06:36 UTC&quot;</code></pre>
<pre class="r"><code>speculation &lt;- bind_rows(comparisons) |&gt;
  filter(query_type == &#39;comparison&#39;) |&gt;
  transmute(topic, year, reference_n, n,
            percentage = comparison_percentage)
head(speculation)</code></pre>
<pre><code>#&gt; # A tibble: 6 × 5
#&gt;   topic               year reference_n     n percentage
#&gt;   &lt;chr&gt;              &lt;int&gt;       &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
#&gt; 1 language evolution  1980           5     0          0
#&gt; 2 language evolution  1981           4     0          0
#&gt; 3 language evolution  1982           4     0          0
#&gt; 4 language evolution  1983           1     0          0
#&gt; 5 language evolution  1984           5     0          0
#&gt; 6 language evolution  1985           6     0          0</code></pre>
<p>The searches were run on 2 September 2026, so the final year is incomplete and its share rests on fewer records than the years before it.</p>
</div>
<div id="results-sizes-of-the-literatures" class="section level2">
<h2>Results: sizes of the literatures</h2>
<p>The nine literatures differ in size by orders of magnitude, and the size matters for reading the percentages. A share computed on a few dozen records moves by several points when one or two abstracts mention speculation, whereas a share computed on thousands of records barely moves at all.</p>
<pre class="r"><code>totals &lt;- speculation |&gt;
  group_by(topic) |&gt;
  summarise(records = sum(reference_n), with_speculation = sum(n),
            share = 100 * with_speculation / records,
            first_year_with_records = min(year[reference_n &gt; 0])) |&gt;
  arrange(desc(share))
totals</code></pre>
<pre><code>#&gt; # A tibble: 9 × 5
#&gt;   topic                           records with_speculation share first_year_with_records
#&gt;   &lt;chr&gt;                             &lt;dbl&gt;            &lt;dbl&gt; &lt;dbl&gt;                   &lt;int&gt;
#&gt; 1 artificial general intelligence    1913               49 2.56                     2006
#&gt; 2 language evolution                 3376               48 1.42                     1980
#&gt; 3 linguistic relativity               739                9 1.22                     1980
#&gt; 4 bilingual advantage                 637                4 0.628                    1993
#&gt; 5 language comprehension             6543               24 0.367                    1980
#&gt; 6 language disorders                14255               36 0.253                    1980
#&gt; 7 language teaching                 22957               42 0.183                    1980
#&gt; 8 hadron collider                   18457               20 0.108                    1980
#&gt; 9 sensorimotor simulation             132                0 0                        2003</code></pre>
<p>Across the whole period, the literature on artificial general intelligence has the highest share of records mentioning speculation (2.6%) and that on sensorimotor simulation the lowest (0.0%), with the language literatures spread between them.</p>
<pre class="r"><code># Nine literatures against an eight-colour palette, so the Okabe-Ito set is
# extended with one grey. Its yellow barely shows against the white background,
# so it is replaced with a wine red, which also stays apart from the orange and
# vermilion lines for colour-blind readers. Nine lines on one panel are hard to
# tell apart by colour alone, so each line is named at its end, and the figure
# that follows gives each literature its own panel.
nine_colours &lt;- c(&#39;#E69F00&#39;, &#39;#56B4E9&#39;, &#39;#009E73&#39;, &#39;#882255&#39;, &#39;#0072B2&#39;,
                  &#39;#D55E00&#39;, &#39;#CC79A7&#39;, &#39;#999999&#39;, &#39;#000000&#39;)

# Years without records are left empty, so that a line breaks there instead of
# bridging the gap, and a year with no records on either side becomes a point.
sizes &lt;- speculation |&gt;
  mutate(records = ifelse(reference_n &gt; 0, reference_n, NA),
         isolated = reference_n &gt; 0 &amp; lag(reference_n, default = 0) == 0 &amp;
           lead(reference_n, default = 0) == 0,
         .by = topic)

ggplot(sizes, aes(year, records, colour = topic)) +
  geom_line(linewidth = 0.8) +
  geom_point(data = filter(sizes, isolated), size = 1.3) +
  # Each label sits at the last year with records, which need not be the
  # current year, since that year is still in progress. The labels take a
  # darker shade of each line&#39;s colour, which reads better as text, and the
  # seed fixes where ggrepel places them.
  ggrepel::geom_text_repel(
    aes(label = topic,
        colour = stage(topic, after_scale = colorspace::darken(colour, 0.25))),
    data = filter(sizes, !is.na(records)) |&gt; filter(year == max(year), .by = topic),
    hjust = 0, direction = &#39;y&#39;, nudge_x = 1.5,
    xlim = c(max(sizes$year) + 1.5, Inf), size = 3.9,
    segment.size = 0.3, box.padding = 0.12, min.segment.length = 0, seed = 1) +
  scale_y_log10(labels = scales::label_comma()) +
  scale_colour_manual(values = nine_colours, guide = &#39;none&#39;) +
  coord_cartesian(clip = &#39;off&#39;) +
  labs(x = NULL, y = &#39;Records per year (log scale)&#39;) +
  theme_minimal(base_size = 13) +
  theme(plot.margin = margin(6, 145, 6, 6))</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/unnamed-chunk-4-1.png" alt="Line chart on a logarithmic axis of the number of Scopus records per year in each of the nine reference literatures from 1980 onwards" width="768" style="display: block; margin: auto;" /></p>
<div id="the-share-of-records-that-mention-speculation" class="section level3">
<h3>The share of records that mention speculation</h3>
<p>Each panel below shows one literature, and the panels are ordered by their overall share, from highest to lowest. The line is the yearly percentage of records that also match <code>speculat*</code>. The shaded band, drawn as a step for each year, is a stability range computed with the Wilson method from the two yearly counts, and it shows how far the share would move with a handful of records. The axis is cut at 15%. Wherever a year’s range would run past that cut, as it does in the early years of several literatures and in many years of the smallest ones, a triangle at the top of the panel takes the place of the band. In the sparsest years, a single abstract would move the share by tens of points. The line itself runs off the top of its panel at the highest share in the data, the 33% that 1 of the 3 records on bilingual advantage in 2006 represent. Years in which a literature has no records break the line.</p>
<pre class="r"><code>wilson &lt;- function(k, n, z = 1.96) {
  p &lt;- k / n
  centre &lt;- (p + z^2 / (2 * n)) / (1 + z^2 / n)
  half &lt;- z * sqrt(p * (1 - p) / n + z^2 / (4 * n^2)) / (1 + z^2 / n)
  data.frame(lower = 100 * pmax(0, centre - half), upper = 100 * pmin(1, centre + half))
}

# Years with no records keep their row but carry NA, so that ggplot2 breaks the
# line there instead of drawing a segment across a gap in the literature.
panel_data &lt;- speculation |&gt;
  mutate(topic = factor(topic, levels = totals$topic)) |&gt;
  bind_cols(wilson(speculation$n, speculation$reference_n)) |&gt;
  mutate(across(c(percentage, lower, upper), ~ ifelse(reference_n &gt; 0, .x, NA_real_)))

panel_labels &lt;- totals |&gt;
  mutate(label = sprintf(&#39;%s\n%s records, %.1f%% with speculat*&#39;,
                         topic, scales::label_comma()(records), share))
labeller_topic &lt;- setNames(panel_labels$label, panel_labels$topic)

# The axis stops at 15%. A band that would run past it is replaced by a
# triangle at the top of the panel, so that the least stable years do not fill
# the panels of the small literatures. Each band is a step one year wide, which
# keeps a single year visible between two years that run past the cut.
y_limit &lt;- 15

ggplot(panel_data, aes(year, percentage)) +
  geom_rect(aes(xmin = year - 0.5, xmax = year + 0.5, ymin = lower, ymax = upper),
            data = filter(panel_data, upper &lt;= y_limit),
            fill = &#39;#0072B2&#39;, alpha = 0.17) +
  geom_point(aes(y = y_limit), data = filter(panel_data, upper &gt; y_limit),
             shape = 17, size = 1.2, colour = &#39;#80B3D8&#39;) +
  geom_line(colour = &#39;#0072B2&#39;, linewidth = 0.7) +
  geom_point(colour = &#39;#0072B2&#39;, size = 0.9) +
  facet_wrap(~ topic, ncol = 3, labeller = as_labeller(labeller_topic)) +
  scale_x_continuous(breaks = c(1980, 2000, 2020)) +
  scale_y_continuous(labels = scales::label_percent(scale = 1)) +
  coord_cartesian(ylim = c(0, y_limit)) +
  labs(x = NULL, y = &#39;Records mentioning speculation (%)&#39;) +
  theme_minimal(base_size = 13) +
  theme(axis.text = element_text(size = rel(0.85)),
        strip.text = element_text(size = rel(0.85), hjust = 0),
        panel.spacing = unit(1.2, &#39;lines&#39;))</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/unnamed-chunk-5-1.png" alt="Nine panels, one per literature, each showing the yearly percentage of Scopus records that mention speculation over the years in which that literature has records, with a shaded Wilson interval for each year and a triangle at the top of the panel wherever the interval runs past the 15 per cent cut of the axis" width="864" style="display: block; margin: auto;" /></p>
<pre class="r"><code>recent &lt;- speculation |&gt;
  filter(year &gt;= 2016, year &lt;= max(year) - 1) |&gt;
  group_by(topic) |&gt;
  summarise(records = sum(reference_n),
            share = 100 * sum(n) / sum(reference_n)) |&gt;
  arrange(desc(share))
recent</code></pre>
<pre><code>#&gt; # A tibble: 9 × 3
#&gt;   topic                           records  share
#&gt;   &lt;chr&gt;                             &lt;dbl&gt;  &lt;dbl&gt;
#&gt; 1 artificial general intelligence    1377 2.54  
#&gt; 2 linguistic relativity               374 1.60  
#&gt; 3 language evolution                 1734 1.56  
#&gt; 4 bilingual advantage                 445 0.449 
#&gt; 5 language comprehension             3298 0.334 
#&gt; 6 language disorders                 6511 0.230 
#&gt; 7 language teaching                 15193 0.178 
#&gt; 8 hadron collider                    7682 0.0781
#&gt; 9 sensorimotor simulation              88 0</code></pre>
<p>Restricting the comparison to the complete years from 2016 onwards, which leaves between 88 and 15,193 records per literature, gives the ranking above. The literature on artificial general intelligence leads, with 2.5% of its records mentioning speculation, and that on sensorimotor simulation closes the list with 0.0%.</p>
</div>
</div>
<div id="discussion-what-the-counts-can-and-cannot-show" class="section level2">
<h2>Discussion: what the counts can and cannot show</h2>
<p>The measure is crude in at least three ways. First, a form of “speculate” in an abstract can be a mark of candour as much as of conjecture. Authors who write “we speculate that” are labelling a claim that others would present without a label, so a literature with a strong convention of hedged abstracts will score higher for that reason alone. Second, the wildcard catches “speculative” in senses that have nothing to do with scientific conjecture, such as speculative execution in computing or speculative investment in economics. Both senses can occur in the literatures on artificial general intelligence and on the hadron collider, whose funding is discussed in economic terms. Third, the queries define each literature by a phrase, so records that belong to a field without using its name are missed. The literatures on language teaching and language disorders, in particular, are far larger than their phrases suggest.</p>
<p>The smallest literature, sensorimotor simulation, contains no record that mentions speculation. With 132 records over the whole period, that absence says more about the size of the literature than about its habits.</p>
<p>With those limits in mind, the differences describe how the records retrieved by these particular queries are worded. The data are most useful as a transparent starting point for reading the records and revising the searches.</p>
</div>
<div id="references" class="section level2">
<h2>References</h2>
<p>Bernabeu, P. (2026). <em>scopusflow: A reproducible workflow layer for Scopus bibliographic searches</em> (Version 0.4.0) [Computer software]. CRAN. <a href="https://doi.org/10.32614/CRAN.package.scopusflow" class="uri">https://doi.org/10.32614/CRAN.package.scopusflow</a></p>
<p>Bernabeu, P., &amp; Vogt, P. (2015, June 18). <em>Language evolution: Current status and future directions</em> [Paper presentation]. 10th Language at the University of Essex Postgraduate Conference (LangUE), Colchester, United Kingdom. <a href="https://eprints.lancs.ac.uk/id/eprint/130664/" class="uri">https://eprints.lancs.ac.uk/id/eprint/130664/</a></p>
<p>Evans, N., &amp; Levinson, S. C. (2009). The myth of language universals: Language diversity and its importance for cognitive science. <em>Behavioral and Brain Sciences</em>, <em>32</em>(5), 429–448. <a href="https://doi.org/10.1017/S0140525X0999094X" class="uri">https://doi.org/10.1017/S0140525X0999094X</a></p>
<p>Tomasello, M. (2009). Universal grammar is dead. <em>Behavioral and Brain Sciences</em>, <em>32</em>(5), 470–471. <a href="https://doi.org/10.1017/S0140525X09990744" class="uri">https://doi.org/10.1017/S0140525X09990744</a></p>
</div>
