---
abstract: 'VTT Transcription App is an open-source, R-based web application that allows the conversion of subtitle files from the Web Video Text Tracks (WebVTT) Format into plain texts. For this purpose, the VTT file (with extension .txt or .vtt) is uploaded to the app. Automatically, metadata such as timestamps are removed, and the text is formatted. Files can be successively submitted and downloaded (as .docx and .txt). As such, this app can serve to make audiovisual content more accessible.'
authors:
date: "2021-01-01"
doi: ""
featured: false
image:
  caption: ''
  focal_point: ""
  preview_only: true
links:
- name: GitHub repository
  url: 'https://github.com/pablobernabeu/VTT-Transcription-App'
- name: Web application
  url: 'https://pablo-bernabeu.shinyapps.io/VTT-Transcription-App/'
#  projects:
# - internal-project
publishDate: "2021-01-01"
publication:
publication_short:
publication_types:
- "1"
# slides: example
summary: ''
categories:
- research and teaching applications
tags:
- subtitles
- accessibility
- transcription
- webvtt
- web video text tracks format
- web application
- data science
- regular expressions
- stringr
- R
- R Shiny
- Flexdashboard
- software
title: 'VTT Transcription App'
url_code: 'https://github.com/pablobernabeu/VTT-Transcription-App'
#url_dataset: ''
# url_pdf: ''
# url_poster: '#'
# url_project: ""
# url_slides: ""
# url_source: '#'
# url_video: '#'
---


```{r eval = TRUE, echo = FALSE, message=FALSE, warning=FALSE}

# Save app version number, to be displayed below. It can be updated at: 
# https://github.com/pablobernabeu/VTT-Transcription-App/blob/main/version-number

app_version = 
  read.delim('https://raw.githubusercontent.com/pablobernabeu/VTT-Transcription-App/main/version-number',
             header = FALSE)[1,1]

```


# VTT Transcription App

**VTT Transcription App** is an open-source, R-based web application that allows the conversion of subtitle files from [Web Video Text Tracks (WebVTT) Format](https://www.w3.org/TR/webvtt1/) into plain texts. For this purpose, users upload a VTT file with extension `.vtt` or `.txt`. Automatically, metadata such as timestamps are removed, and the text is formatted into a paragraph. The result is displayed on the website, and can be downloaded as `.docx` and `.txt` documents. Overall, this application serves to improve the accessibility of subtitles.

## :globe_with_meridians:&nbsp; The web application can be [launched here](https://pablo-bernabeu.shinyapps.io/VTT-Transcription-App/) or [here](https://mybinder.org/v2/gh/pablobernabeu/VTT-Transcription-App/HEAD?urlpath=shiny)

The data is only available to the user, and is deleted when the website is closed.

Questions and suggestions can be submitted as [issues](https://github.com/pablobernabeu/VTT-transcription/issues) or emailed to p.bernabeu@lancaster.ac.uk. The app can be extended via pull requests.

Developer: Pablo Bernabeu (Dept. Psychology, Lancaster University). Licence: [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/).

## Code details

The core of the application is in the [index.Rmd](https://github.com/pablobernabeu/VTT-Transcription-App/blob/main/index.Rmd) script, which uses '[regular expressions](https://stringr.tidyverse.org/articles/regular-expressions.html)' to process the VTT file. In turn, that script draws on [another one](https://github.com/pablobernabeu/VTT-Transcription-App/blob/main/VTT-Transcription-App_doc_renderer.Rmd) to enable the download of `.docx` documents. Last, the latter script in turn uses a [Word template](https://github.com/pablobernabeu/VTT-Transcription-App/blob/main/VTT-Transcription-App-format-template.docx).

<br>