---
title: Motivating a preregistration (especially in experimental linguistics)
author: ''
date: '2023-11-24'
slug: motivating-a-preregistration-especially-in-experimental-linguistics
categories:
  - research-methods
tags:
  - prereg
  - preregistration
  - research methods
  - s
subtitle: ''
summary: 'The best argument to motivate a preregistration may be that it doesn’t take any extra time. It just requires frontloading an important portion of the work. As a reward, the paper will receive greater trust from the reviewers and the readers at large. Preregistration is not perfect, but is a lesser evil that reduces the misuse of statistical analysis in science.'
authors: []
lastmod: ''
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


## The disorder

Studies in the cognitive sciences often feature multiple experimental conditions. Once the study progresses, the analytical liberties associated with so many experimental conditions are compounded by the myriad possible steps in data processing and analysis (*the garden of forking paths*). As a result, the researcher degrees of freedom often soar to unexpected highs. The system of professional incentives in academia largely ignores the issue of researcher degrees of freedom. When CVs are assessed, quantity weighs more than quality of research. When studies are assessed, statistical significance weighs more than methodological rigour. Thus, the low replication rates in various fields, including linguistics (Kobrock & Roettger, 2023), are hardly surprising (cf. Barsalou, 2019). 

## The treatment

The purpose of a preregistration is to reduce the number of researcher degrees of freedom. The best argument to motivate a preregistration may be that it doesn’t take any extra time. It just requires frontloading an important portion of the work. As a reward, preregistered analyses are received with greater trust by peer-reviewers and other readers. Preregistration is not perfect, but is a lesser evil that reduces the misuse of statistical analysis in science (Mertzen et al., 2021; Roettger, 2023).

The preregistration takes a bit of time, which poses a challenge because funding mandates often require *doing things* as soon as possible (i.e., academic capitalism). However, if any contributors of a project can gather just enough time and interest to initiate a preregistration before data collection (or before the analysis, in the case of meta-analyses and secondary-data analyes), then the researchers can attempt to pocket the important asset of preregistration for their study. They will reap the reward in time, and so will their field of research at large.

### What to do

Initially, rather than detailed analytical steps, it is the broader theoretical aspects that should be laid out. An abstract and an introduction should be written, describing why the study has been designed in such a way, what analyses will be performed, and what hypotheses are afforded by the literature. Next, some methodological details regarding the materials and the analyses should be added.

The degree of detail in the preregistration can be determined by the researchers alone. Yet, ceteris paribus, the greater the detail in a preregistration, the greater the trustworthiness of the analyses and the results. Multiple preregistration guidelines exist by now, including some field-specific ones.

### Solace

Rules are made to be broken---at least as and when necessary. That is, deviations from the preregistration are possible, and indeed very frequent (Bakker et al., 2020; van den Akker et al., 2023).

> Even the strongest blizzards start with a single snowflake. (Sara Raasch) 

## References

Bakker, M., Veldkamp, C. L. S., Assen, M. A. L. M. van, Crompvoets, E. A. V., Ong, H. H., Nosek, B. A., Soderberg, C. K., Mellor, D., & Wicherts, J. M. (2020). Ensuring the quality and specificity of preregistrations. *PLOS Biology, 18*(12), e3000937. https://doi.org/10.1371/journal.pbio.3000937

Barsalou, L. W. (2019). Establishing generalizable mechanisms. *Psychological Inquiry, 30*(4), 220–230. https://doi.org/10.1080/1047840X.2019.1693857

Kobrock, K., & Roettger, T. B. (2023). Assessing the replication landscape in experimental linguistics. *Glossa Psycholinguistics, 2*(1). https://doi.org/10.5070/G6011135

Mertzen, D., Lago, S., & Vasishth, S. (2021). The benefits of preregistration for hypothesis-driven bilingualism research. *Bilingualism: Language and Cognition, 24*(5), 807–812. https://doi.org/10.1017/S1366728921000031

Roettger, T. B. (2021). Preregistration in experimental linguistics: Applications, challenges, and limitations. *Linguistics, 59*(5), 1227–1249. https://doi.org/10.1515/ling-2019-0048

van den Akker, O. R., van Assen, M. A. L. M., Enting, M., de Jonge, M., Ong, H. H., Rüffer, F., Schoenmakers, M., Stoevenbelt, A. H., Wicherts, J. M., & Bakker, M. (2023). Selective hypothesis reporting in psychology: Comparing preregistrations and corresponding publications. *Advances in Methods and Practices in Psychological Science, 6*(3), 25152459231187988. https://doi.org/10.1177/25152459231187988

