---
title: 'WebVTT caption transcription app'
type: software
software_kind: web-application
aliases:
  - '/applications-and-dashboards/vtt-transcription-app/'
diagram: true
abstract: "This open-source, R-based web application converts video captions (subtitles) from the Web Video Text Tracks (WebVTT) Format into plain text. Users upload a WebVTT file with the extension .vtt or .txt, and the application automatically removes metadata such as timestamps and formats the text."
authors:
date: "2021-01-01"
doi: "10.5281/zenodo.10615960"
featured: false
image:
  caption: ''
  focal_point: ""
  preview_only: true
links:
- name: GitHub repository
  url: 'https://github.com/pablobernabeu/VTT-Transcription-App'
- name: Web application
  url: 'https://pablo-bernabeu.shinyapps.io/VTT-Transcription-App/'
#  projects:
# - internal-project
publishDate: "2021-01-01"
publication:
publication_short:
# slides: example
summary: 'Open-source, R-based application that converts video captions from the WebVTT format into plain text, automatically removing timestamps and formatting the content into accessible documents.'
categories:
- research and teaching applications
- web application
- R
tags:
- subtitles
- accessibility
- transcription
- webvtt
- web video text tracks format
- web application
- data science
- regular expressions
- stringr
- R
- R Shiny
- Flexdashboard
- software
open_materials: true
url_code: 'https://github.com/pablobernabeu/VTT-Transcription-App/blob/main/index.Rmd'
#url_data: ''
# url_fulltext: ''
# url_poster: '#'
# url_project: ""
# url_slides: ""
# url_source: '#'
# url_video: '#'
---


## How It Works

The diagram below outlines how the application turns a caption file into a plain-text document.

```{=html}
<div class="mermaid">
graph TD
  A["User uploads WebVTT file<br/>(vtt or txt)"] --> B["Regular expressions remove<br/>metadata such as timestamps"]
  B --> C["Text formatted<br/>into a paragraph"]
  C --> D["Result displayed<br/>on the website"]
  D --> E["Download as docx<br/>or txt document"]
</div>
```
The application accepts caption files in the [Web Video Text Tracks (WebVTT) Format](https://www.w3.org/TR/webvtt1/) with the extension `.vtt` or `.txt`, such as [this example](https://github.com/pablobernabeu/VTT-Transcription-App/blob/main/assets/Example_subtitles_1.vtt) or [this one](https://github.com/pablobernabeu/VTT-Transcription-App/blob/main/assets/Example_subtitles_2.txt).

<script src="https://emgithub.com/embed-v2.js?target=https%3A%2F%2Fgithub.com%2Fpablobernabeu%2FVTT-Transcription-App%2Fblob%2Fee3031eca0fccfce3aafe6b07233d97e923d9d15%2Fassets%2FExample_subtitles_1.vtt&style=a11y-dark&type=code&showLineNumbers=on&showFileMeta=on&showCopy=on&fetchFromJsDelivr=on"></script>

[**Download VTT file**](https://osf.io/download/ustmx)

Once a caption file is uploaded, the application removes metadata such as timestamps and formats the text into a paragraph. The result is displayed on the page and can be downloaded as a `.docx` or `.txt` document. In this way, the application makes the content of video captions more accessible. The uploaded data are available only to the user and are deleted when the page is closed.

## <i class="fa-solid fa-globe"></i>&nbsp;Web Application

The application can be used below or [opened in a separate window](https://pablo-bernabeu.shinyapps.io/VTT-Transcription-App).

<div style = 'margin-bottom: 25px;'>
<div style = 'position: relative; padding-top: 56.25%; height: 1100px;'>
<iframe title="Application: WebVTT caption transcription app" src = 'https://pablo-bernabeu.shinyapps.io/VTT-Transcription-App' frameborder = '0' allowfullscreen style = 'position: absolute; top: 0; left: 0; width: 100%; height: 100%;'></iframe>
</div>
</div>

## Programming Details

The [source code is available on GitHub](https://github.com/pablobernabeu/VTT-Transcription-App) under a [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/) licence, and the app can be extended through pull requests. The code is also archived on Zenodo (Bernabeu, 2024). Questions and suggestions can be submitted as [issues](https://github.com/pablobernabeu/VTT-Transcription-App/issues) or emailed to pcbernabeu@gmail.com.

The core of the application is the [index.Rmd](https://github.com/pablobernabeu/VTT-Transcription-App/blob/main/index.Rmd) script, which processes the VTT file with [regular expressions](https://stringr.tidyverse.org/articles/regular-expressions.html).

<script src="https://emgithub.com/embed-v2.js?target=https%3A%2F%2Fgithub.com%2Fpablobernabeu%2FVTT-Transcription-App%2Fblob%2Fee3031eca0fccfce3aafe6b07233d97e923d9d15%2Findex.Rmd%23L163-L225&style=a11y-dark&type=code&showLineNumbers=on&showFileMeta=on&showCopy=on&fetchFromJsDelivr=on"></script>

To produce `.docx` documents, that script renders [the one below](https://github.com/pablobernabeu/VTT-Transcription-App/blob/main/assets/VTT-Transcription-App_doc_renderer.Rmd), which in turn applies the format of [this Word template](https://github.com/pablobernabeu/VTT-Transcription-App/blob/main/assets/VTT-Transcription-App-format-template.docx).

<script src="https://emgithub.com/embed-v2.js?target=https%3A%2F%2Fgithub.com%2Fpablobernabeu%2FVTT-Transcription-App%2Fblob%2Fee3031eca0fccfce3aafe6b07233d97e923d9d15%2Fassets%2FVTT-Transcription-App_doc_renderer.Rmd%23L1-L18&style=a11y-dark&type=code&showLineNumbers=on&showFileMeta=on&showCopy=on&fetchFromJsDelivr=on"></script>

## References

Bernabeu, P. (2024). *VTT-Transcription-App* (Version 0.2) [Computer software]. Zenodo. [https://doi.org/10.5281/zenodo.10674606](https://doi.org/10.5281/zenodo.10674606)

