name: Spell Check

on:
  push:
    paths:
      - "content/**/*.md"
      - "content/**/*.Rmd"
  pull_request:
    paths:
      - "content/**/*.md"
      - "content/**/*.Rmd"
  workflow_dispatch: # Allow manual triggering

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Check spelling
        uses: crate-ci/typos@bee27e3a4fd1ea2111cf90ab89cd076c870fce14 # v1.48.0
        with:
          config: .typos.toml
          files: content/
